services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
